AuthenticationWeb/AuthenticationWeb/Models/UserModel.cs
using AuthenticationWeb.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AuthenticationWeb.Models
{
    public class UserModel
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string UserPassword { get; set; }

        [Required]
        public UserType UserType { get; set; }
    }
}

AuthenticationWeb/AuthenticationWeb/Controllers/AccountsController.cs
using AuthenticationBusiness.UserBusiness;
using AuthenticationWeb.Common;
using AuthenticationWeb.Models;
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.ComponentModel;
using AuthenticationWeb.CustomAttribute;

namespace AuthenticationWeb.Controllers
{
    public class AccountsController : Controller
    {
        IApplicationBusiness _business;

        public AccountsController(IApplicationBusiness business)
        {
            _business = business;
        }

        [AppAuthorizeRoutingAttribute]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _business.UserLogin(model.UserName, model.UserPassword);
                if (user != null)
                {
                    FormsAuthentication.SetAuthCookie(model.UserName, false);

                    var authTicket = new FormsAuthenticationTicket(1, user.UserName, DateTime.Now, DateTime.Now.AddMinutes(20), false, ((UserType)user.UserType).ToString());
                    string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                    var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    HttpContext.Response.Cookies.Add(authCookie);

                    if ((int)UserType.Admin == user.UserType)
                    {
                        return RedirectToAction("Index", "Admin");
                    }

                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError("", DataCommon.InvalidLogin);
                return View(model);
            }

            ModelState.AddModelError("", DataCommon.InvalidLogin);
            return View(model);
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        [AppAuthorizeRoutingAttribute]
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(UserModel model)
        {
            if (ModelState.IsValid)
            {
                if (_business.ValidateExistUser(model.UserName))
                {
                    ModelState.AddModelError("", DataCommon.ExistUser);
                    return View(model); ;
                }

                var user = _business.UserSignUp(model.UserName, model.UserPassword, (int)model.UserType);

                if (user != null)
                {
                    // Auto login after signing up user success
                    FormsAuthentication.SetAuthCookie(model.UserName, false);

                    var authTicket = new FormsAuthenticationTicket(1, user.UserName, DateTime.Now, DateTime.Now.AddMinutes(20), false, ((UserType)user.UserType).ToString());
                    string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                    var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    HttpContext.Response.Cookies.Add(authCookie);

                    if ((int)UserType.Admin == user.UserType)
                    {
                        return RedirectToAction("Index", "Admin");
                    }

                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError("", DataCommon.InvalidSignup);
                return View(model);
            }

            ModelState.AddModelError("", DataCommon.InvalidSignup);
            return View(model);
        }
    }
}

AuthenticationWeb/AuthenticationWeb/Controllers/AdminController.cs
using AuthenticationWeb.CustomAttribute;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AuthenticationWeb.Controllers
{
    [Authorize]
    [AppAuthorizeRoutingAttribute]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

AuthenticationWeb/AuthenticationWeb/Controllers/HomeController.cs
using AuthenticationBusiness;
using AuthenticationBusiness.UserBusiness;
using AuthenticationWeb.CustomAttribute;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AuthenticationWeb.Controllers
{
    [Authorize]
    [AppAuthorizeRoutingAttribute]
    public class HomeController : Controller
    {
        IApplicationBusiness _business;
        public HomeController(IApplicationBusiness business)
        {
            _business = business;
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

AuthenticationWeb/AuthenticationWeb/Views/Accounts/Login.cshtml
@model AuthenticationWeb.Models.UserModel
@{
    ViewBag.Title = "Login";
}
<h2>Login</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("If you don't have a account, click here to Signup", "Signup")
</div>

AuthenticationWeb/AuthenticationWeb/Views/Accounts/SignUp.cshtml
@model AuthenticationWeb.Models.UserModel
@{
    ViewBag.Title = "Signup";
}
<h2>Signup</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Password", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("User Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.UserType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Signup" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Click here to Login", "Login")
</div>

AuthenticationWeb/AuthenticationWeb/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>This is Admin page</h2>

AuthenticationWeb/AuthenticationWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>This is Home Page</h2>

AuthenticationWeb/AuthenticationWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NAL TEST APPLICATION", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a>Hello - @User.Identity.Name</a></li>
                        <li>@Html.ActionLink("Logout", "Logout", "Accounts")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Accounts")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>